name: Lint and Test

on:
  push:
    paths:
      - src/**/*.ts
      - types/**/*.ts
      - tests/**/*.ts
      - .eslint*
      - .prettier*
      - "*.json"

env:
  NODE_VERSION: 16

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Prettier Check
        run: npm run fmt:check

      - name: ESLint
        run: npm run lint

      - name: Jest
        run: npm test
