name: Lint and Test

on:
  pull_request:
    types: [opened, reopened]
    branches: [master]
  push:
    branches: ['*']

env:
  NODE_VERSION: 16

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Prettier Check
        run: npm run fmt

      - name: ESLint
        run: npm run lint

      - name: Jest
        run: npm test
